### ISSUE TITLE
Set compiler flags at the beginning

### ISSUE THREAD

**Issue by fbruetting** [mrhanky17/pyload-freebsd#13]
At the moment, I have to confirm the compiler flags for every port when it's compiled. There is an option so that all compiler flags of all ports are shown to the user before compiling the first program. This would let the user confirm all flags in a row and then the compilation can run on the system until it's end without interrupting the process. Please integrate this option!

Also the existence of all needed ports should be checked before loading/compiling/installing a port, so that the afore mentioned improvement doesn't work per pyload-dependency but for all dependencies as a whole.

**Comment by Mask66** [comment]
That has nothing to do with the port itself. Have a look at https://www.freebsd.org/doc/handbook/ports-using.html and the portmaster/portupgrade/synth utilities.
